version: '3.8'
services:
  flask-container:
    build: ./flask
    container_name: flask-container
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    #network_mode: 'host'
    ports:
      - 8080:8080/tcp
    volumes:
      - ./flask:/usr/src/app

  postgresql-container:
    image: postgres:14
    container_name: postgresql-container
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5433:5432'
    volumes:
      - postgresql_vol:/var/lib/postgresql/data

volumes:
  postgresql_vol:
