version: '3.8'
services:
  fastapi-container:
    build: ./fastapi
    container_name: fastapi-container
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    command: uvicorn run:fastapi_app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080/tcp
    volumes:
      - ./fastapi:/usr/src/app

  postgresql-container:
    image: postgres:14
    container_name: postgresql-container
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=shop
      - TZ=GMT+8
      - PGTZ=GMT+8
    ports:
      - '5433:5432'
    volumes:
      - postgresql_vol:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgresql_vol:
